# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

# baseURL = "https://your_domain.com/"
baseURL = 'https://mnjm.github.io/kayal'
languageCode = 'en-us'
title = 'Kayal'
theme = "kayal"

enableRobotsTXT = true
paginate = 10
summaryLength = 70

buildDrafts = true
buildFuture = false

enableEmoji = true

# [services]
#   [services.googleAnalytics]
#     ID = 'G-MEASUREMENT_ID'
