# -- Main Menu --

# The menus are displayed in the header at the top of the page.
# Acceptable parameters are name, page, url, pre, weight.

# Add a training '/' to local urls.
# For ex: /posts/
# NOT: /posts

# `pre` is a icon id. for list of all available icons check [https://github.com/mnjm/kayal/tree/main/assets/icons]

[[main]]
name = "Docs"
title = "Docs"
url = "/docs/"
weight = 1

[[main]]
name = "Examples"
title = "Examples"
url = "/examples/"
weight = 2

[[main]]
name = "Shortcodes"
title = "Shortcodes"
url = "/shortcodes/"
weight = 3

[[main]]
name = "GitHub"
title = ""
pre = "github"
url = "https://github.com/mnjm/kayal"
weight = 4
